### ISSUE TITLE
ToDo's

### ISSUE THREAD

**Issue by skjerns** [CIMH-Clinical-Psychology/MEG-highspeed-task#1]
TODO:

General
- [x] make sure reward is meaningful (3.6€ in original study)
    - [x] check reward is mentioned correctly in text
- [x] check number of distractors ==20? 20 vs 25er debruijn
- [x] check stimuli distribution and total runtime is not extreme with random ISIs
- [x] check sequences are well distributed across participants
- [x] add short pseudorest after fast sequences? max buffer is enough for analysis?
- [x] make sound start and stop
- [ ] ~~"Sequences were chosen such that each visual object appeared equally often at the first and last position of the sequence."~~ ???
- [x] Questionnaires?
- [x] Do digitspan or not?
- [x] change RS to full time frame
- [ ] ~~record button presses with triggers?~~ difficult with psychopy

Coding
- [x] resting state
- [x] breaks between blocks
- [x] check output once
- [x] check timings are correct (no "duration" anywhere in code, all with variables in GUI)
